import {
  FaWhatsapp,
  FaPhone,
  FaPhoneFlip,
  FaEnvelope,
  FaLocationDot,
  FaArrowRight,
  FaArrowRightLong,
  FaCheck,
  FaStar,
  FaBars,
  FaXmark,
  FaPlay,
  FaChevronLeft,
  FaChevronRight,
  FaChevronDown,
  FaLeaf,
  FaGlobe,
  FaTruckFast,
  FaTruck,
  FaBox,
  FaBoxesStacked,
  FaShieldHalved,
  FaHandshake,
  FaClipboardCheck,
  FaClipboardList,
  FaFileLines,
  FaShip,
  FaMortarPestle,
  FaHotel,
  FaIndustry,
  FaSeedling,
  FaCircleCheck,
  FaMagnifyingGlass,
  FaGears,
  FaUserTie,
  FaDroplet,
  FaScaleBalanced,
  FaLayerGroup,
  FaCalendarCheck,
  FaEye,
  FaEyeDropper,
  FaTag,
  FaRulerCombined,
  FaPaintbrush,
  FaListCheck,
  FaSuitcase,
  FaBoxOpen,
  FaRotate,
  FaMessage,
} from "react-icons/fa6";

const iconMap = {
  whatsapp: FaWhatsapp,
  phone: FaPhone,
  "phone-flip": FaPhoneFlip,
  email: FaEnvelope,
  location: FaLocationDot,
  arrow: FaArrowRight,
  "arrow-long": FaArrowRightLong,
  check: FaCheck,
  star: FaStar,
  bars: FaBars,
  close: FaXmark,
  play: FaPlay,
  "chevron-left": FaChevronLeft,
  "chevron-right": FaChevronRight,
  "chevron-down": FaChevronDown,
  leaf: FaLeaf,
  globe: FaGlobe,
  "truck-fast": FaTruckFast,
  truck: FaTruck,
  box: FaBox,
  "boxes-stacked": FaBoxesStacked,
  shield: FaShieldHalved,
  handshake: FaHandshake,
  "clipboard-check": FaClipboardCheck,
  "clipboard-list": FaClipboardList,
  "file-lines": FaFileLines,
  ship: FaShip,
  spices: FaMortarPestle,
  hotel: FaHotel,
  factory: FaIndustry,
  seedling: FaSeedling,
  "circle-check": FaCircleCheck,
  search: FaMagnifyingGlass,
  gears: FaGears,
  "user-tie": FaUserTie,
  droplet: FaDroplet,
  scale: FaScaleBalanced,
  layers: FaLayerGroup,
  calendar: FaCalendarCheck,
  eye: FaEye,
  "eye-dropper": FaEyeDropper,
  tag: FaTag,
  ruler: FaRulerCombined,
  brush: FaPaintbrush,
  "list-check": FaListCheck,
  suitcase: FaSuitcase,
  "box-open": FaBoxOpen,
  rotate: FaRotate,
  message: FaMessage,
};

export function Icon({ name, size = 20, ...rest }) {
  const Cmp = iconMap[name] || FaLeaf;
  return <Cmp size={size} {...rest} />;
}
